source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-default-layout"
  gem "jekyll-optional-front-matter"
  gem "jekyll-algolia"
  gem "liquid-md5"
  gem "jekyll-datapage-generator"
  gem "jekyll-tagging-related_posts"
  gem "jekyll-loading-lazy"
  gem "jekyll-timeago"
  gem "jekyll-mentions"
  gem "jekyll-twitter-plugin"
  gem "jekyll-seo-tag"
  gem "jekyll-redirect-from"
  gem "jekyll-analytics"
  gem "emoji_for_jekyll"
  gem "jekyll-paspagon"
  gem "jekyll-admin"
  gem "jekyll_version_plugin"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

